name: Vue

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
          node-version: '18'
    - name: npm install
      run: |
        npm install

    - name: npm build
      run: npm run build --if-present

    - name: npm test
      id: tests
      run: |
        npm run test:unit --passWithNoTests
      env:
        CI: true
